name             'base'
maintainer       'Warachet Samtalee'
maintainer_email 'di.warachet@gmail.com'
license          'All rights reserved'
description      'Installs/Configures base'
version          '0.1.0'
